version: '3.8'

services:

  leaderboard-service-db:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: haris123
      POSTGRES_DB: leaderboard
    volumes:
      - exam_data:/var/lib/postgresql/data
    ports:
      - "4444:5432"

volumes:
  exam_data: