server:
  port: 3000
  read_timeout: 3
  write_timeout: 5

db:
  host: localhost
  port: 2222
  user: postgres
  password: haris123
  db_name: exam
  ssl_mode: disable
  min_conn: 3
  max_conn: 200

kafka:
  broker: localhost:9092
